import argparse

from data_set_merge import DataSetMerge
from pathlib import Path


def main():
    args_parser = argparse.ArgumentParser(
        description='merge resources generated by cppminer to a code2seq dataset')

    args_parser.add_argument('OutPath',
                             metavar='out',
                             type=str,
                             help='the output path')

    args_parser.add_argument('-c', '--clear_resources',
                             metavar='flag',
                             type=bool,
                             help='if True clear resource files',
                             default=False,
                             required=False)

    args = args_parser.parse_args()

    output_path = Path(args.OutPath).resolve().as_posix()
    print('Path: ' + output_path)

    print('Clear resources: ' + str(args.clear_resources))

    # shuffle and merge samples
    print("Merging samples ...")
    merge = DataSetMerge(output_path)
    merge.merge(args.clear_resources)
    print("Dumping datasets ...")
    merge.dump_datasets(0.7)
    print("Merging done")


if __name__ == '__main__':
    main()
